### ISSUE TITLE
Wrong or no code snippets for queries using $count

### ISSUE THREAD

**Issue by FaithOmbongi** [microsoftgraph/microsoft-graph-devx-api#818] opened 2021-12-08 09:33 UTC
**Describe the bug**
Checking the examples in docs or even testing the examples in Graph Explorer, we notice that the code snippets for examples that include `$count`/`$count=true` are incorrect. The two scenarios are:

1. When `$count` is used as a path parameter (e.g. `/users/$count`), the code snippet is incorrect. [_Update: identified a related issue to track this: https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/402)_]
2. When `$count` is used as a query parameter (e.g. `/users?$count=true`), the code snippet doesn't show use of `$count` and is incorrect

**To Reproduce** (where `$count=true` is used)

1. Click the following request to run in Graph Explorer [https://graph.microsoft.com/v1.0/users?$filter=endswith(mail,'a@contoso.com')&$orderby=userPrincipalName&$count=true](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24filter%3Dendswith(mail%2C'a%40contoso.com')%26%24orderby%3DuserPrincipalName%26%24count%3Dtrue&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d)
2. See code snippet responses below for Java and CSharp showing that `$count` isn't included

```csharp
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var users = await graphClient.Users
	.Request()
	.Filter("endswith(mail,'a@contoso.com')")
	.OrderBy("userPrincipalName")
	.GetAsync();
```

```java
GraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

UserCollectionPage users = graphClient.users()
	.buildRequest()
	.filter("endswith(mail,'a@contoso.com')")
	.orderBy("userPrincipalName")
	.get();
```

**To Reproduce** (where `/$count` is used)

1. Click the following request to run in Graph Explorer [https://graph.microsoft.com/v1.0/groups/$count](https://developer.microsoft.com/en-us/graph/graph-explorer?request=groups%2F%24count&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d)
2. See code snippet responses below for Java and CSharp that are incorrect

```csharp
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var int32 = await graphClient.Groups.$count
	.Request()
	.GetAsync();
```

```java
GraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

int int32 = graphClient.groups().count()
	.buildRequest()
	.get();
```

**Expected behavior**
The code snippets should be complete and/or accurate

**Additional context**
The problem also affects code snippets in docs. Examples:
 - [Example 5 in List users](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#example-5-use-filter-to-get-all-users-with-a-mail-that-ends-with-acontosocom-including-a-count-of-returned-objects-with-the-results-ordered-by-userprincipalname)
 - [Example 2 in List groups](https://docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&tabs=http#example-2-get-a-filtered-list-of-groups-including-the-count-of-returned-objects)

cc @Licantrop0

**Comment by zengin** [comment] 2021-12-09 03:14
closing as duplicate of #497

**Closed by zengin** 2021-12-09 03:14 UTC
Labels: Area:snippet generation
