### ISSUE TITLE
Snippet generation repeats thumbnailSet-id incorrectly for indexing size

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/microsoft-graph-devx-api#744] opened 2021-10-22 03:53 UTC
HTTP snippet:
```http
GET /me/drive/items/{item-id}/thumbnails/{thumb-id}/{size}/content
```

C# snippet:
```csharp
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var content = await graphClient.Me.Drive.Items["{driveItem-id}"].Thumbnails["{thumbnailSet-id}"]["{thumbnailSet-id}"].Content
	.Request()
	.GetAsync();
```

Second `thumbnailSet-id` should be `size-id`.

**Comment by zengin** [comment] 2021-11-19 23:22
This is an edge case given that there are two ID-like field one after the other in the URL and ID naming depends on the previous non-ID-like path segment.

**Comment by ddyett** [comment] 2023-04-05 22:21
don't see a snippet for the path under thumbnails.

**Comment by millicentachieng** [comment] 2023-07-03 02:16
Duplicate of #1486

**Closed by millicentachieng** 2023-07-03 02:16 UTC
Labels: status: duplicate, area: snippets generation
