### ISSUE TITLE
Run tests in CI/CD against the endpoints

### ISSUE THREAD

**Issue by thewahome** [microsoftgraph/microsoft-graph-devx-api#1251] opened 2022-11-15 15:01 UTC
**Is your feature request related to a problem? Please describe.**
When developing, we need tests that confirm that the known payloads from DevX API clients like Graph Explorer always return the expected results

**Describe the solution you'd like**
Controller unit testing
- Have unit tests that run against the specific controllers of the GraphWebApi project
- Use known payloads to run the tests

**Describe alternatives you've considered**
Live site testing
- Deploy a live environment when we commit to dev 
- Make XHR requests against the endpoints with known payloads
- Validate that the responses are as expected

**Comment by millicentachieng** [comment] 2023-07-03 11:08
Duplicate of #856

**Closed by millicentachieng** 2023-07-03 11:08 UTC
Labels: status: duplicate, type: enhancement
